import type { ServiceDetail } from '@vinc/api';

function inDays(days: number, hour: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

/** Demo-mode service details, keyed by the mock agenda commitment ids. */
export const DEMO_SERVICES: Record<string, ServiceDetail> = {
  '1': {
    id: '1',
    title: 'Faxina — Casa da Ana',
    description: 'Limpeza completa do apartamento, produtos fornecidos.',
    status: 'accepted',
    role: 'worker',
    startsAt: inDays(0, 14),
    endsAt: inDays(0, 17),
    priceCents: 12000,
    area: 'Boa Vista, Recife',
    approxLat: -8.0585,
    approxLng: -34.8752,
    address: 'Rua das Flores, 100 — Boa Vista, Recife',
    lat: -8.0611,
    lng: -34.872,
    counterpartId: 'demo-ana',
    counterpartName: 'Ana Souza',
    workerNoShow: false,
  },
  '2': {
    id: '2',
    title: 'Babá — 2 crianças',
    description: 'Crianças de 4 e 7 anos, jantar incluído.',
    status: 'completed',
    role: 'worker',
    startsAt: inDays(1, 15),
    endsAt: inDays(1, 22),
    priceCents: 16000,
    area: 'Centro, Recife',
    approxLat: -8.0551,
    approxLng: -34.8858,
    address: 'Av. Central, 45 — Centro, Recife',
    lat: -8.0578,
    lng: -34.8829,
    counterpartId: 'demo-ana',
    counterpartName: 'Ana Souza',
    workerNoShow: false,
  },
  '4': {
    id: '4',
    title: 'DJ para aniversário (minha vaga)',
    description: 'Festa de 15 anos, 4 horas de música.',
    status: 'pending_approval',
    role: 'poster',
    startsAt: inDays(2, 20),
    endsAt: inDays(2, 23),
    priceCents: 30000,
    area: 'Graças, Recife',
    approxLat: -8.0436,
    approxLng: -34.8981,
    address: 'Salão Primavera — Graças, Recife',
    lat: -8.0463,
    lng: -34.8952,
    counterpartId: 'demo-joao',
    counterpartName: 'João Pedro',
    workerNoShow: false,
  },
  '3': {
    id: '3',
    title: 'Garçom para festa (minha vaga)',
    description: 'Festa para 40 pessoas.',
    status: 'awaiting_confirmation',
    role: 'poster',
    startsAt: inDays(3, 18),
    endsAt: inDays(3, 23),
    priceCents: 20000,
    area: 'Jardim América, Recife',
    approxLat: -8.0497,
    approxLng: -34.8801,
    address: 'Salão Jardim América — Jardim América, Recife',
    lat: -8.0525,
    lng: -34.877,
    counterpartId: 'demo-paulo',
    counterpartName: 'Paulo Dias',
    workerNoShow: false,
  },
  '5': {
    id: '5',
    title: 'Passear com cachorro (minha vaga)',
    description: 'Passeio de 1 hora com cachorro dócil de porte médio.',
    status: 'open',
    role: 'poster',
    startsAt: inDays(0, 18),
    endsAt: inDays(0, 19),
    priceCents: 5000,
    area: 'Madalena, Recife',
    approxLat: -8.0471,
    approxLng: -34.9014,
    address: 'Praça da Matriz, 10 — Madalena, Recife',
    lat: -8.0498,
    lng: -34.8987,
    counterpartId: null,
    counterpartName: null,
    workerNoShow: false,
  },
  '6': {
    id: '6',
    title: 'Fotógrafo para evento (minha vaga)',
    description: 'Cobertura de 3 horas de um evento corporativo.',
    status: 'accepted',
    checkinCode: '4821',
    role: 'poster',
    startsAt: inDays(4, 9),
    endsAt: inDays(4, 12),
    priceCents: 24000,
    area: 'Salgadinho, Olinda',
    approxLat: -8.0841,
    approxLng: -34.8973,
    address: 'Centro de Convenções — Salgadinho, Olinda',
    lat: -8.0868,
    lng: -34.8945,
    counterpartId: 'demo-joao',
    counterpartName: 'João Pedro',
    workerNoShow: false,
  },
};
