-- Vinc — Fase 2 bloco 2.6: in-app notification center
--
-- Notifications are generated by DATABASE TRIGGERS on the events that
-- already exist (candidacies, gig status, escrow releases, disputes) —
-- not by the Edge Functions — so the pg_cron jobs (expiration, 48h
-- auto-release, 12h auto-awaiting) notify exactly like user actions do.
-- The app builds the pt-BR text from `type` + the gig title; real push
-- arrives with the EAS build (Fase 4).

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  gig_id uuid references public.gigs (id) on delete cascade,
  type text not null check (type in (
    'new_candidate', 'chosen', 'not_chosen',
    'service_started', 'service_completed', 'payment_released',
    'dispute_opened', 'dispute_resolved',
    'cancelled_by_poster', 'cancelled_by_worker', 'gig_expired'
  )),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;

create policy "users read their own notifications"
  on public.notifications for select to authenticated
  using (user_id = (select auth.uid()));

-- Marking as read is the ONLY client write (column privilege below).
create policy "users mark their own notifications read"
  on public.notifications for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

revoke update on public.notifications from authenticated;
grant update (read_at) on public.notifications to authenticated;

-- ============================================================ triggers

-- Candidacies: someone applied (→ poster); chosen / not chosen (→ worker).
create or replace function public.notify_candidacy()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  gig_poster uuid;
begin
  if tg_op = 'INSERT' and new.status = 'pending' then
    select poster_id into gig_poster from gigs where id = new.gig_id;
    insert into notifications (user_id, gig_id, type)
      values (gig_poster, new.gig_id, 'new_candidate');
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    if new.status = 'chosen' then
      insert into notifications (user_id, gig_id, type)
        values (new.worker_id, new.gig_id, 'chosen');
    elsif new.status = 'not_chosen' then
      insert into notifications (user_id, gig_id, type)
        values (new.worker_id, new.gig_id, 'not_chosen');
    end if;
  end if;
  return new;
end;
$$;

create trigger notify_candidacy
  after insert or update on public.gig_candidacies
  for each row execute function public.notify_candidacy();

-- Gig status: start/complete (→ poster), cancellations and expiration.
-- (open → accepted is covered by the candidacy 'chosen' notification;
-- releases are covered by the ledger trigger below.)
create or replace function public.notify_gig_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = old.status then return new; end if;
  if new.status = 'in_progress' then
    insert into notifications (user_id, gig_id, type)
      values (new.poster_id, new.id, 'service_started');
  elsif new.status = 'awaiting_confirmation' then
    insert into notifications (user_id, gig_id, type)
      values (new.poster_id, new.id, 'service_completed');
  elsif new.status = 'cancelled_by_poster' and new.worker_id is not null then
    insert into notifications (user_id, gig_id, type)
      values (new.worker_id, new.id, 'cancelled_by_poster');
  elsif new.status = 'cancelled_by_worker' then
    insert into notifications (user_id, gig_id, type)
      values (new.poster_id, new.id, 'cancelled_by_worker');
  elsif new.status = 'expired' then
    insert into notifications (user_id, gig_id, type)
      values (new.poster_id, new.id, 'gig_expired');
  end if;
  return new;
end;
$$;

create trigger notify_gig_status
  after update of status on public.gigs
  for each row execute function public.notify_gig_status();

-- Money in: any escrow release (confirmation, 48h job, dispute leftover).
create or replace function public.notify_release()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.type = 'escrow_release' and new.amount_cents > 0 then
    insert into notifications (user_id, gig_id, type)
      values (new.user_id, new.gig_id, 'payment_released');
  end if;
  return new;
end;
$$;

create trigger notify_release
  after insert on public.ledger_entries
  for each row execute function public.notify_release();

-- Disputes: opened (→ worker), resolved (→ both).
create or replace function public.notify_dispute()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  gig_record record;
begin
  select poster_id, worker_id into gig_record from gigs where id = new.gig_id;
  if tg_op = 'INSERT' then
    if gig_record.worker_id is not null then
      insert into notifications (user_id, gig_id, type)
        values (gig_record.worker_id, new.gig_id, 'dispute_opened');
    end if;
  elsif tg_op = 'UPDATE' and new.status = 'resolved' and old.status = 'open' then
    insert into notifications (user_id, gig_id, type)
      values (gig_record.poster_id, new.gig_id, 'dispute_resolved');
    if gig_record.worker_id is not null then
      insert into notifications (user_id, gig_id, type)
        values (gig_record.worker_id, new.gig_id, 'dispute_resolved');
    end if;
  end if;
  return new;
end;
$$;

create trigger notify_dispute
  after insert or update on public.disputes
  for each row execute function public.notify_dispute();
